id = "tomorrow-min-theme"
name = "Tomorrow Minimal Theme"
version = "1.1.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Fork of [Tomorrow Theme](https://github.com/biaqat/tomorrow-theme-zed) with less highlights."
repository = "https://github.com/biaqat/tomorrow-min-theme-zed"
